import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Box from "@mui/material/Box";
import { getSession } from "@/lib/auth";
import { StoreProvider } from "@/store/StoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pedal N' Path",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await getSession();

  return (
    <StoreProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Header session={user} />
          <Box sx={{ mt: 8 }}>{children}</Box>
        </body>
      </html>
    </StoreProvider>
  );
}
